### ISSUE TITLE
[Функция] Автопереподключение при потере соединения или timeout-е

### ISSUE THREAD

**Issue by veselcraft** [tinelix/irc-client#4]
Это вызывается плохим интернетом, или закрытием крышки ноутбука

**Comment by tretdm** [comment]
Добавлено к версии 0.4.2 (29 августа 2021 г.), пока только с номером ошибки 60.

**Comment by tretdm** [comment]
Забыл сказать, что в последнем коммите уже реализован реконнект для кодов ошибок: -3 и 100.
![2021-08-31-21-47-08](https://user-images.githubusercontent.com/76806170/131524433-c69db1b2-0610-4129-8f4d-80aa1c22c5fe.png)
